mindspore-lab/mindyolo

deploy/infer.py, deploy/infer_engine/lite.py, deploy/infer_engine/mindx.py
=> fix deploy bug

deploy/GETTING_STARTED.md, deploy/README.md, deploy/export.py, deploy/infer_engine/lite.py, deploy/infer_engine/mindx.py, deploy/infer_engine/model_base.py, deploy/predict.py, deploy/reqirements.txt, deploy/test.py, mindyolo/models/heads/yolov3_head.py, mindyolo/models/heads/yolov5_head.py, mindyolo/models/heads/yolov7_head.py
fix some bugs in deploy
add readme about environment and usage
add requirements and getting start for deploy
add configs that needed in om convert
add infer.py that can infer one image
=> add deploy infer and readme

deploy/README.md
Found some requirements when deploy mindx environment.
=> update mindx requirements

README.md
fix Supported Algorithms in README.md
=> fix Supported Algorithms in README.md

mindyolo/models/__init__.py, mindyolo/models/model_factory.py
add yolov4 for init file and model_factory
=> add yolov4 for init file and model_factory

mindyolo/models/heads/yolov3_head.py, mindyolo/models/heads/yolov5_head.py, mindyolo/models/heads/yolov7_head.py, mindyolo/models/heads/yolov8_head.py, mindyolo/models/layers/utils.py
=> fix meshgrid bug in depoly.

mindyolo/models/model_factory.py, mindyolo/optim/group_params.py
=> Model parsing adding key-value pairing method configuration parameters

deploy/GETTING_STARTED.md, deploy/README.md
yolov4 & yolov8n ckpt are ready, deploy need to follow
=> update deploy yolov4 & v8n

GETTING_STARTED.md
=> revise GETTING_STARTED.md

MODEL_ZOO.md, configs/yolox/README.md, configs/yolox/yolox-m-2nd.yaml
1. add s and m scale weight of yolox
2. add readme of yolox
Closes #94
=> add s and m scale to yolox

GETTING_STARTED_CN.md
=> Add GettingStart.md Chinese version

mindyolo/utils/config.py, train.py
1. fix bug config log
Closes #97
=> fix bug of config log

GETTING_STARTED.md, GETTING_STARTED_CN.md, MODEL_ZOO.md, configs/yolov3/README.md, configs/yolov4/README.md, configs/yolov5/README.md, configs/yolov7/README.md, configs/yolov8/README.md, configs/yolox/README.md, mindyolo/models/losses/iou_loss.py, mindyolo/models/losses/yolov7_loss.py, mindyolo/utils/metrics.py
=> Add yolov8-s/m/l weight and modify some docs

README.md, README_CN.md
=> Add README.md Chinese version

GETTING_STARTED.md
=> remove a useless colon

deploy/README.md
=> update yolov8&yolov4 deploy weight

GETTING_STARTED_CN.md, train.py, tutorials/modelarts_CN.md
=> add tutorials/modelarts_CN.md

mindyolo/models/yolov7.py
=> fix a yolov7 bug

tutorials/modelarts.md, tutorials/modelarts_CN.md
=> Add modelart tutorial EN version and revise CN version

configs/yolov8/hyp.scratch.high.yaml, configs/yolov8/hyp.scratch.low.yaml, configs/yolov8/hyp.scratch.med.yaml, configs/yolov8/yolov8-base.yaml, mindyolo/data/loader.py, mindyolo/models/heads/yolov3_head.py, mindyolo/models/heads/yolov5_head.py, mindyolo/models/heads/yolov7_head.py, mindyolo/models/heads/yolov8_head.py, mindyolo/models/heads/yolox_head.py, mindyolo/models/layers/bottleneck.py, mindyolo/models/layers/utils.py, mindyolo/models/losses/iou_loss.py, mindyolo/models/losses/yolov3_loss.py, mindyolo/models/losses/yolov4_loss.py, mindyolo/models/losses/yolov5_loss.py, mindyolo/models/losses/yolov7_loss.py, mindyolo/models/losses/yolov8_loss.py, mindyolo/models/losses/yolox_loss.py, mindyolo/optim/ema.py, mindyolo/utils/train_step_factory.py, mindyolo/utils/trainer_factory.py, mindyolo/utils/utils.py, train.py
=> Adapt to MindSpore2.0

mindyolo/utils/callback.py, mindyolo/utils/registry.py, mindyolo/utils/trainer_factory.py
1. set a trace for registry
closes #130
=> show path of registry modules

examples/finetune_SHWD/README.md, examples/finetune_SHWD/finetune_shwd.py, examples/finetune_SHWD/yolov7-tiny_shwd.yaml, tests/modules/test_create_group_param.py, tests/modules/test_create_loss.py, tests/modules/test_create_model.py, tests/modules/test_create_optimizer.py, tests/modules/test_create_trainer.py
=> add modules test

mindyolo/version.py
=> fix mindyolo/version.py to r0.1

README.md, README_CN.md, mkdocs.yml
=> amend the link of a pic

.github/workflows/ci.yml, requirements/cpu_requirements.txt, tests/modules/test_create_trainer.py
=> enable test cases

README.md, README_CN.md, docs/en/INSTALLATION.md, docs/zh/INSTALLATION_CN.md, mindyolo/csrc/__init__.py, mindyolo/csrc/build.sh, mindyolo/csrc/fast_coco_eval/__init__.py, mindyolo/csrc/fast_coco_eval/cocoeval/cocoeval.cpp, mindyolo/csrc/fast_coco_eval/cocoeval/cocoeval.h, mindyolo/csrc/fast_coco_eval/fast_coco_eval_api.py, mindyolo/csrc/setup.py, requirements.txt, setup.py, test.py
1. to speed up coco map calculation
close #163 
=> add fast coco eval api

deploy/__init__.py, tests/modules/test_deploy_predict.py
=> add deploy predict test

docs/en/tutorials/modelarts.md, docs/zh/tutorials/modelarts.md, requirements/docs.txt
=> amend mkdocs's verison

demo/__init__.py, mindyolo/utils/metrics.py, requirements/cpu_requirements.txt, tests/modules/test_demo_predict.py
module test environment is on cpu, deploy need 310 environment, so I changed to demo predict test unit
it can test on cpu and has same logic with deploy predict
=> update deploy predict to demo predict

mindyolo/utils/utils.py, train.py
=> support non-strict load of pretrain model

mindyolo/models/heads/yolov4_head.py
=> fix yolov4 EvalWhileTrain bug

deploy/README.md
=> fix a typo & and a note

README.md, configs/yolov8/seg/yolov8-seg-base.yaml, configs/yolov8/seg/yolov8x-seg.yaml, deploy/test.py, mindyolo/data/albumentations.py, mindyolo/data/dataset.py, mindyolo/utils/trainer_factory.py, mindyolo/utils/utils.py, test.py, tests/modules/test_create_trainer.py, train.py
=> fix yolov8x-seg bug

GETTING_STARTED.md, configs/yolov3/hyp.scratch.yaml, configs/yolov4/hyp.scratch.yaml, configs/yolov5/hyp.scratch-high.yaml, configs/yolov5/hyp.scratch-low.yaml, configs/yolov7/hyp.scratch.p5.yaml, configs/yolov7/hyp.scratch.p6.yaml, configs/yolov7/hyp.scratch.tiny.yaml, configs/yolov8/hyp.scratch.high.yaml, configs/yolov8/hyp.scratch.low.yaml, configs/yolov8/hyp.scratch.med.yaml, configs/yolox/hyp.scratch.yaml, mindyolo/data/dataset.py, mindyolo/data/utils.py
=> Detection task adapt new data processing

mindyolo/utils/poly.py, tests/dataset_plots.py
=> fix detection label visualization

mindyolo/models/heads/yolov7_head.py
=> fix meshgrid in version 2.1

mindyolo/data/utils.py
=> fix yolov8-seg non-overlap data format bug

RELEASE.md, mindyolo/version.py
=> update r0.2 version and RELEASE.md

mindyolo/data/utils.py
=> fix data.utils.segment2box bug

mindyolo/utils/metrics.py, test.py
=> modify _clip_coords to in-place operation

GETTING_STARTED_CN.md, configs/yolov3/README.md, configs/yolov4/README.md, configs/yolov5/README.md, configs/yolov7/README.md, configs/yolov8/README.md, configs/yolox/README.md, deploy/README.md
=> modify links of document

.gitee/ISSUE_TEMPLATE/Documentation.yml, .gitee/ISSUE_TEMPLATE/Intern.yml, .gitee/ISSUE_TEMPLATE/Requirement.yml, .gitee/ISSUE_TEMPLATE/Task-Tracking.yml, .gitee/ISSUE_TEMPLATE/ThirdParty.yml, .gitee/ISSUE_TEMPLATE/bug_report.yml, .gitee/ISSUE_TEMPLATE/config.yml, .gitee/ISSUE_TEMPLATE/feature.yml, .gitee/ISSUE_TEMPLATE/question.yml, .gitee/PULL_REQUEST_TEMPLATE.md
=> add issue template

train.py
- [x ] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindyolo/blob/master/CONTRIBUTING.md)
- [x ] Your code builds clean without any errors or warnings
- [ x] You are using approved terminology
- [ x] You have added unit tests
fix OOM of run_eval mode
#242
=> fix OOM of run_eval mode

mindyolo/utils/metrics.py
single label will get error:
got an unexpected keyword argument 'keepdim'
=> fix  single label error

mindyolo/data/dataset.py
=>  fix hw_scale keyerror

README.md, README_CN.md
=> modify supported mindspore edition

mindyolo/version.py
=> Modify mindyolo version to 0.3.0

mindyolo/version.py, setup.py
=> fix setup.py

mindyolo/data/dataset.py
=> fix np.int

configs/yolov8/yolov8s.yaml
=> avoid forced update for yolov8s

mindyolo/models/losses/yolox_loss.py, tests/modules/test_create_loss.py
=> fix yolox_loss num_class to nc

requirements/cpu_requirements.txt
=> limit ci numpy version

demo/predict.py, mindyolo/utils/utils.py, test.py
Reverts mindspore-lab/mindyolo#296
=> Revert "use GE backend for graph mode"

demo/predict.py, mindyolo/utils/utils.py, test.py
=> add jit config level O2 for training scripts to support ms 2.3.0 version

demo/predict.py, mindyolo/utils/utils.py, test.py
=> add jit config level O2 for training scripts

configs/yolov8/yolov8n.yaml
=> avoid forced update for yolov8n

docs/zh/index.md
=> fix docs deploy

README.md
=> remove device type from version table

configs/yolov8/yolov8l.yaml, configs/yolov8/yolov8m.yaml, configs/yolov8/yolov8x.yaml
=> avoid force update for yolov8l yolov8m yolov8x

configs/yolov3/README.md, configs/yolov4/README.md, configs/yolov5/README.md, configs/yolov7/README.md, configs/yolov8/README.md, configs/yolox/README.md
There is a problem with the relative paths of the config files of the model in the original respective readme.
So, the prefixed paths need to be removed.
=> fix relative path problem in readme

mindyolo/data/dataset.py
=> fix yolo data iteration error

configs/yolov3/README.md, configs/yolov4/README.md, configs/yolov5/README.md, configs/yolov7/README.md, configs/yolov8/README.md, configs/yolox/README.md
There is a problem with the relative paths of the config files of the model in the original respective readme.
So, the prefixed paths need to be removed.
=> fix relative problem in readme

GETTING_STARTED.md, GETTING_STARTED_CN.md, configs/yolov3/README.md, configs/yolov4/README.md, configs/yolov5/README.md, configs/yolov7/README.md, configs/yolov8/README.md, configs/yolox/README.md, docs/en/modelzoo/yolov3.md, docs/en/modelzoo/yolov4.md, docs/en/modelzoo/yolov5.md, docs/en/modelzoo/yolov7.md, docs/en/modelzoo/yolov8.md, docs/en/modelzoo/yolox.md, docs/en/tutorials/configuration.md, docs/en/tutorials/finetune.md, docs/en/tutorials/quick_start.md, docs/zh/modelzoo/yolov3.md, docs/zh/modelzoo/yolov4.md, docs/zh/modelzoo/yolov5.md, docs/zh/modelzoo/yolov7.md, docs/zh/modelzoo/yolov8.md, docs/zh/modelzoo/yolox.md, docs/zh/tutorials/configuration.md, docs/zh/tutorials/finetune.md, docs/zh/tutorials/quick_start.md, examples/finetune_SHWD/README.md, examples/finetune_car_detection/README.md, tutorials/configuration_CN.md
=> adjust to msrun command

GETTING_STARTED.md, GETTING_STARTED_CN.md, configs/yolov3/README.md, configs/yolov4/README.md, configs/yolov5/README.md, configs/yolov7/README.md, configs/yolov8/README.md, configs/yolox/README.md
=> add bind-to numa to improve performance

demo/predict.py, test.py
Reverts mindspore-lab/mindyolo#347
=> Revert "fix yolov7's MaxPool2d bug"

demo/predict.py, test.py
Reverts mindspore-lab/mindyolo#346
=> Revert "fix yolov7's MaxPool2d's bug"

configs/yolov7/yolov7-tiny.yaml, test.py
=> fix yolov7's MaxPool2d's bug

configs/yolov8/seg/yolov8-seg-base.yaml, mindyolo/data/dataset.py
=> fix yolov8x-segment bug

configs/yolov8/seg/yolov8-seg-base.yaml, configs/yolov8/yolov8-base.yaml, mindyolo/data/dataset.py, train.py
=> fix yolov8x-segment bug and fix scale for loss hyps

train.py
=> fix yolox attribute error

GETTING_STARTED.md, README.md, configs/yolov3/README.md, configs/yolov4/README.md, configs/yolov5/README.md, configs/yolov7/README.md, configs/yolov8/README.md, configs/yolox/README.md
=> update readme for mindspore version of 2.3.1

examples/finetune_car_detection/crejson.py, examples/finetune_carparts_seg/README.md, examples/finetune_carparts_seg/create_anno.py, examples/finetune_carparts_seg/predict.py, examples/finetune_carparts_seg/rename.py, examples/finetune_carparts_seg/yolov8x-seg_carparts.yaml
=> add carparts seg example

deploy/mslite_predict.py, examples/finetune_carparts_seg/predict.py, examples/finetune_visdrone/predict.py, test.py, train.py
=> fix is_coco_dataset judgment condition

GETTING_STARTED.md, GETTING_STARTED_CN.md, configs/yolov10/README.md, configs/yolov3/README.md, configs/yolov4/README.md, configs/yolov5/README.md, configs/yolov7/README.md, configs/yolov8/README.md, configs/yolov9/README.md, configs/yolox/README.md, examples/finetune_SHWD/README.md, tutorials/configuration_CN.md
=> remove gpu's description in md

deploy/README.md
=> add readme for converting to mslite mindir file

demo/predict.py
https://github.com/mindspore-lab/mindyolo/issues/405
=> predictr v10 without running nms

demo/predict.py, mindyolo/utils/metrics.py
=> update predict for v9\v10

.github/workflows/ci.yml, demo/predict.py, mindyolo/data/dataset.py, mindyolo/utils/metrics.py
=> Update predict.py for  support v9\v10

mindyolo/data/dataset.py
=> fix sample['segments'] bug 

GETTING_STARTED.md, GETTING_STARTED_CN.md, README.md, configs/yolov10/README.md, configs/yolov3/README.md, configs/yolov4/README.md, configs/yolov5/README.md, configs/yolov7/README.md, configs/yolov8/README.md, configs/yolov9/README.md, configs/yolox/README.md, docs/en/index.md, docs/en/modelzoo/yolov3.md, docs/en/modelzoo/yolov4.md, docs/en/modelzoo/yolov5.md, docs/en/modelzoo/yolov7.md, docs/en/modelzoo/yolov8.md, docs/en/modelzoo/yolox.md, docs/zh/index.md, docs/zh/modelzoo/yolov3.md, docs/zh/modelzoo/yolov4.md, docs/zh/modelzoo/yolov5.md, docs/zh/modelzoo/yolov7.md, docs/zh/modelzoo/yolov8.md, docs/zh/modelzoo/yolox.md, examples/finetune_SHWD/README.md, examples/finetune_single_class_dataset/README.md, examples/finetune_visdrone/README.md
=> update readme for ms2.5.0

README.md, configs/yolov11/README.md, configs/yolov11/hyp.scratch.l.yaml, configs/yolov11/hyp.scratch.m.yaml, configs/yolov11/hyp.scratch.n.yaml, configs/yolov11/hyp.scratch.s.yaml, configs/yolov11/hyp.scratch.x.yaml, configs/yolov11/yolov11-base.yaml, configs/yolov11/yolov11-l.yaml, configs/yolov11/yolov11-m.yaml, configs/yolov11/yolov11-n.yaml, configs/yolov11/yolov11-s.yaml, configs/yolov11/yolov11-x.yaml, mindyolo/data/dataset.py, mindyolo/data/utils.py, mindyolo/models/__init__.py, mindyolo/models/heads/__init__.py, mindyolo/models/heads/yolov11_head.py, mindyolo/models/layers/__init__.py, mindyolo/models/layers/bottleneck.py, mindyolo/models/layers/conv.py, mindyolo/models/losses/__init__.py, mindyolo/models/losses/yolov11_loss.py, mindyolo/models/model_factory.py, mindyolo/models/yolov11.py
=> add yolo11

demo/predict.py, deploy/export.py, examples/finetune_carparts_seg/predict.py, examples/finetune_visdrone/predict.py, mindyolo/utils/utils.py, test.py
=> fix set_device twice bug

deploy/export.py, mindyolo/models/layers/activation.py, mindyolo/models/layers/bottleneck.py, mindyolo/models/layers/conv.py
=> SiLU adapt ONNX

mindyolo/csrc/fast_coco_eval/fast_coco_eval_api.py, mindyolo/data/dataset.py, mindyolo/data/utils.py, mindyolo/models/registry.py
=> add copyright
