mindspore-lab/mindyolo

- MODEL_ZOO.md
- configs/yolov5/README.md
> Add yolov5x weight

- GETTING_STARTED.md
- GETTING_STARTED_CN.md
- examples/finetune_SHWD/README.md
- examples/finetune_SHWD/convert_shwd2yolo.py
- examples/finetune_SHWD/convert_yolov7-tiny_pretrain_ckpt.py
- examples/finetune_SHWD/finetune_shwd.py
- examples/finetune_SHWD/yolov7-tiny_shwd.yaml
- mindyolo/utils/config.py
- train.py
- tutorials/custom_dataset.md
> add finetune tutorial

- train.py
- tutorials/configuration_CN.md
> add configuration.md

- mindyolo/utils/callback.py
- mindyolo/utils/logger.py
- mindyolo/utils/trainer_factory.py
- mindyolo/utils/utils.py
- test.py
- train.py
1. support online & ofline distributed  inference to increase inference speed
closes #142 
> support online & ofline distributed  inference

- mindyolo/data/dataset.py
- requirements/cpu_requirements.txt
- tests/modules/test_create_loader.py
- tests/modules/test_create_trainer.py
> add test_create_loader

- docs/zh/how_to_guides/write_a_new_model.md
> add write a new model file

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> update issue template

- docs/en/installation.md
- docs/zh/installation.md
- mindyolo/models/losses/fused_op/__init__.py
- mindyolo/models/losses/fused_op/build.sh
- mindyolo/models/losses/fused_op/elementswise_op_impl.cu
- mindyolo/models/losses/fused_op/fused_get_boundding_boxes_coord_kernel.cu
- mindyolo/models/losses/fused_op/fused_get_center_dist_kernel.cu
- mindyolo/models/losses/fused_op/fused_get_ciou_diagonal_angle_kernel.cu
- mindyolo/models/losses/fused_op/fused_get_ciou_kernel.cu
- mindyolo/models/losses/fused_op/fused_get_convex_diagonal_squared_kernel.cu
- mindyolo/models/losses/fused_op/fused_get_intersection_area_kernel.cu
- mindyolo/models/losses/fused_op/fused_get_iou_kernel.cu
- mindyolo/models/losses/iou_loss.py
- mindyolo/models/losses/yolov3_loss.py
- mindyolo/models/losses/yolov4_loss.py
- mindyolo/models/losses/yolov5_loss.py
- mindyolo/models/losses/yolov7_loss.py
- mindyolo/models/losses/yolov8_loss.py
- mindyolo/models/losses/yolox_loss.py
- mindyolo/utils/utils.py
- setup.py
- train.py
Using MindSpore ops.Custom to accelerate computing bbox_iou on GPU platform.
> add aot custom op to accelerate computing bbox_iou on GPU

- mindyolo/models/heads/yolov5_head.py
- mindyolo/models/yolov3.py
- mindyolo/models/yolov4.py
- mindyolo/models/yolov5.py
- mindyolo/models/yolov7.py
- mindyolo/models/yolov8.py
- mindyolo/models/yolox.py
> Modify simple use cases in model definition

- deploy/MINDIR.md
- deploy/ONNX.md
- deploy/ONNXRuntime.md
- deploy/README.md
- deploy/infer_engine/__init__.py
- deploy/infer_engine/mindir.py
- deploy/infer_engine/onnxruntime.py
- deploy/predict.py
add mindspore native graph infer & onnx runtime infer engine  
since after mindspore 2.x, mindspore is able to infer mindIR model in GraphMode without other python pkgs
--
--
> add mindspore native graph infer & onnx runtime infer engine

- configs/yolox/hyp.scratch.yaml
- configs/yolox/yolox-nano.yaml
- configs/yolox/yolox-tiny.yaml
- mindyolo/data/dataset.py
> fix yolox yaml

- demo/predict.py
- mindyolo/utils/utils.py
- test.py
> use GE backend for graph mode

- demo/predict.py
- test.py
It occured MaxPool2d failed when running test.py or predict.py in 910*.
So need to be circumvented by modifying the script, but this is ops's bug, which only support int and fp16.
This pr needs to be updated when ops's demand is done.
> fix yolov7's MaxPool2d bug

- demo/predict.py
- test.py
It occured MaxPool2d failed when running test.py or predict.py in 910*.
So need to be circumvented by modifying the script, but this is ops's bug, which only support int and fp16.
This pr needs to be updated when ops's demand is done.
> fix yolov7's MaxPool2d's bug

- GETTING_STARTED.md
- GETTING_STARTED_CN.md
- configs/yolov3/README.md
- configs/yolov4/README.md
- configs/yolov5/README.md
- configs/yolov7/README.md
- configs/yolov8/README.md
- configs/yolox/README.md
- examples/finetune_SHWD/README.md
- tutorials/configuration_CN.md
> adjust to msrun command

- README.md
- docs/zh/how_to_guides/data_preparation.md
- examples/finetune_car_detection/crejson.py
- examples/finetune_car_detection/rename.py
- examples/finetune_car_detection/voc2yolo.py
- examples/finetune_single_class_dataset/README.md
- examples/finetune_single_class_dataset/yolov8n_single_class_dataset.yaml
- requirements/cpu_requirements.txt
> add finetune single_class_dataset

- train.py
> add scale for loss hyps

- mindyolo/data/albumentations.py
pip install -r requriment.txt, will download high version albumentations. such as 1.4.18, which causes differences of sample['cls'] shape of (n, ). This changes here adjust sample['cls'] shape to (n,1) 
https://github.com/mindspore-lab/mindyolo/issues/370
> fix difference of high version albumentations

- mindyolo/data/albumentations.py
pip install -r requriment.txt, will download high version albumentations. such as 1.4.18, which causes differences of sample['cls'] shape of (n, ). This changes here adjust sample['cls'] shape to (n,1)
https://github.com/mindspore-lab/mindyolo/issues/370
> fix difference bewtween high version albumentations

- configs/yolov8/yolov8-base.yaml
- train.py
> fix scale for loss hyps

- examples/finetune_SHWD/README.md
- examples/finetune_car_detection/README.md
- examples/finetune_single_class_dataset/README.md
- examples/finetune_visdrone/README.md
- examples/finetune_visdrone/predict.py
- examples/finetune_visdrone/yolov8-l-visdrone.yaml
> add version info for examples

- configs/yolov10/hyp.scratch.high.yaml
- configs/yolov10/hyp.scratch.low.yaml
- configs/yolov10/hyp.scratch.med.yaml
- configs/yolov3/hyp.scratch.yaml
- configs/yolov4/hyp.scratch.yaml
- configs/yolov5/hyp.scratch-high.yaml
- configs/yolov5/hyp.scratch-low.yaml
- configs/yolov7/hyp.scratch.p5.yaml
- configs/yolov7/hyp.scratch.p6.yaml
- configs/yolov7/hyp.scratch.tiny.yaml
- configs/yolov8/hyp.scratch.high.yaml
- configs/yolov8/hyp.scratch.low.yaml
- configs/yolov8/hyp.scratch.med.yaml
- configs/yolov8/seg/hyp.scratch.high.seg.yaml
- configs/yolov9/hyp.scratch.high.yaml
- configs/yolox/hyp.scratch.yaml
- docs/en/tutorials/configuration.md
- docs/zh/tutorials/configuration.md
- mindyolo/data/dataset.py
- mindyolo/data/loader.py
- mindyolo/utils/trainer_factory.py
- tutorials/configuration_CN.md
> improve yolo performance

- demo/predict.py
https://github.com/mindspore-lab/mindyolo/issues/405
> predictr v10 without running nms
